/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.doctorrole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MedicalPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalPrescriptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    private Patient patient;
    private Encounter encounter;
    public MedicalPrescriptionJPanel(JPanel userProcessContainer,UserAccount account,Enterprise enterprise,EcoSystem system,Patient patient,Encounter encounter) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        this.system=system;
        this.patient=patient;
        this.encounter=encounter;
        
        populateNetworkcombo();
        //populateTable();
    }
    
    public void populateNetworkcombo(){
        networkjComboBox.removeAllItems();
        for (Network network : system.getNetworkList()) {
            networkjComboBox.addItem(network);
        }
    }
    
    public void populatePharmacyCombo(Network network){
        pharmacyjComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if(enterprise.getEnterpriseType().getValue().equals("Pharmacy"))
            pharmacyjComboBox.addItem(enterprise);
        }
    }
    
    public void populateDrugsCombo(PharmacyEnterprise enterprise){
        drugjComboBox.removeAllItems();
        for(Drug drug:enterprise.getDrugList().getDrugList()){
            drugjComboBox.addItem(drug);
        }
    }
    
//    public void populateTable(){
//        DefaultTableModel dtm = (DefaultTableModel)medicalprejTable.getModel();
//        dtm.setRowCount(0);
//        
//        for(Encounter encounter:patient.getEncounterList().getEncounterList()){
//            Object[] row = new Object[3];
//            row[0]=encounter.getMedication().getDrug();
////            Enterprise enterprise1=(Enterprise)pharmacyjComboBox.getSelectedItem();
////            row[1]=enterprise1;
//            row[1]=encounter.getMedication().getDosage();
//            dtm.addRow(row);
//            
//        }
        
        
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pharmacyjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        dosagejTextField = new javax.swing.JTextField();
        prescribejButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        networkjComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        drugjComboBox = new javax.swing.JComboBox();
        backjButton1 = new javax.swing.JButton();
        viewcommunicationjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Pharmacy");

        pharmacyjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pharmacyjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyjComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Dosage");

        prescribejButton.setText("Prescribe");
        prescribejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescribejButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Network");

        networkjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Drugs");

        drugjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        viewcommunicationjButton.setText("View Communication Plan");
        viewcommunicationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcommunicationjButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Medical Prescription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(viewcommunicationjButton)
                        .addGap(45, 45, 45)
                        .addComponent(prescribejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pharmacyjComboBox, 0, 97, Short.MAX_VALUE)
                                    .addComponent(networkjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drugjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dosagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(networkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pharmacyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drugjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dosagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescribejButton)
                    .addComponent(viewcommunicationjButton))
                .addGap(61, 61, 61)
                .addComponent(backjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBoxActionPerformed
        // TODO add your handling code here:
        Network network=(Network)networkjComboBox.getSelectedItem();
        if(network!=null){
            populatePharmacyCombo(network);
        }
    }//GEN-LAST:event_networkjComboBoxActionPerformed

    private void pharmacyjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyjComboBoxActionPerformed
        // TODO add your handling code here:
         Enterprise enterprise=(Enterprise)pharmacyjComboBox.getSelectedItem();
         PharmacyEnterprise e1=(PharmacyEnterprise)enterprise;
        if(enterprise!=null){
            populateDrugsCombo(e1);
        }
        
    }//GEN-LAST:event_pharmacyjComboBoxActionPerformed

    private void prescribejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescribejButtonActionPerformed
        // TODO add your handling code here:
        int dosage = Integer.parseInt(dosagejTextField.getText());
        if (dosage==0) {
            JOptionPane.showMessageDialog(null, "Please enter Dosage");
            return;
        } 
            Network network=(Network)networkjComboBox.getSelectedItem();
            Enterprise enterprise1=(Enterprise)pharmacyjComboBox.getSelectedItem();
            Drug drug=(Drug)drugjComboBox.getSelectedItem();
            encounter.getMedication().setDrug(drug);
            encounter.getMedication().setDosage(dosage);
            encounter.getMedication().setPharmacy((PharmacyEnterprise) enterprise1);
            patient.getEncounterList().getEncounterList().add(encounter);
            //populateTable();
        
    }//GEN-LAST:event_prescribejButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void viewcommunicationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcommunicationjButtonActionPerformed
        // TODO add your handling code here:
        Drug drug=(Drug)drugjComboBox.getSelectedItem();
//        System.out.println(drug.getCommunicationPlan().getCommunicationPlan());
//        System.out.println(drug.getCommunicationPlan());
//        System.out.println(drug);
        if(drug.getCommunicationPlan().getCommunicationPlan()== null){
            JOptionPane.showMessageDialog(null, "No Communication Plan for this Drug");
            return;
        }
        ViewCommunicationPlanJPanel vcpjp = new ViewCommunicationPlanJPanel(userProcessContainer,enterprise,drug.getCommunicationPlan());
        userProcessContainer.add("ViewCommunicationPlanJPanel", vcpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewcommunicationjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField dosagejTextField;
    private javax.swing.JComboBox drugjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox networkjComboBox;
    private javax.swing.JComboBox pharmacyjComboBox;
    private javax.swing.JButton prescribejButton;
    private javax.swing.JButton viewcommunicationjButton;
    // End of variables declaration//GEN-END:variables
}
