/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.doctorrole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.QualityAnalystOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdverseEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class RaiseAdverseEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RaiseAdverseEventJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    public RaiseAdverseEventJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system=system;
        populateTable();
        populateNetworkCombo();
    }
    
    public void populateNetworkCombo(){
        networkjComboBox.removeAllItems();
        for(Network network:system.getNetworkList()){
            networkjComboBox.addItem(network);
        }
    }
    
    public void populateDrugCompanyCombo(Network network){
        drugCompanyjComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if(enterprise.getEnterpriseType().getValue().equals("DrugCompany"))
            drugCompanyjComboBox.addItem(enterprise);
        }
    }
    
    public void populateDrugCombo(DrugCompanyEnterprise enterprise){
        drugjComboBox.removeAllItems();
        for(Drug drug:enterprise.getDrugList().getDrugList()){
            drugjComboBox.addItem(drug);
        }
    }
    
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) adversejTable.getModel();
        dtm.setRowCount(0);
        
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if(request instanceof AdverseEventWorkRequest){
            Object[] row=new Object[6];
            row[0]=request;
            row[1]=request.getSender();
            row[2]=request.getReceiver()==null?null:request.getReceiver();
            row[3]=request.getStatus();
            AdverseEventWorkRequest req=(AdverseEventWorkRequest)request;
            row[4]=req.getDrug().getDrugName();
            row[5]=req.getDrugCompany().getName();
            dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        networkjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        drugCompanyjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        drugjComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        adversejTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        messagejTextField = new javax.swing.JTextField();
        sendjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Network");

        networkjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Drug Company");

        drugCompanyjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugCompanyjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCompanyjComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Drug");

        drugjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adversejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Doctor Name", "QA Name", "Status", "Drug Name", "Drug Company"
            }
        ));
        jScrollPane1.setViewportView(adversejTable);

        jLabel4.setText("Message");

        sendjButton.setText("Send ");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Raise Adverse Event");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(networkjComboBox, 0, 96, Short.MAX_VALUE)
                            .addComponent(drugCompanyjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drugjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(messagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendjButton)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(networkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drugCompanyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drugjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(messagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendjButton)
                    .addComponent(jButton1))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBoxActionPerformed
        // TODO add your handling code here:
        Network network=(Network)networkjComboBox.getSelectedItem();
        if(network!=null){
            populateDrugCompanyCombo(network);
        }
    }//GEN-LAST:event_networkjComboBoxActionPerformed

    private void drugCompanyjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCompanyjComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise=(Enterprise)drugCompanyjComboBox.getSelectedItem();
        DrugCompanyEnterprise e1=(DrugCompanyEnterprise)enterprise;
        if(e1!=null){
            populateDrugCombo(e1);
        }
    }//GEN-LAST:event_drugCompanyjComboBoxActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
        String message = messagejTextField.getText();
        if (messagejTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Work Request");
            return;
        }
        AdverseEventWorkRequest request=new AdverseEventWorkRequest();
        Enterprise ent=(Enterprise)drugCompanyjComboBox.getSelectedItem();
        DrugCompanyEnterprise e1=(DrugCompanyEnterprise)ent;
        Drug d=(Drug)drugjComboBox.getSelectedItem();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        request.setDrug(d);
        request.setDrugCompany(e1);
        
        Organization org=null;
        
        for(Organization o:e1.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof QualityAnalystOrganization){
                org=o;
                break;
            }
        }
        if(org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        System.out.println(account.getWorkQueue().getWorkRequestList().size());
        populateTable();
        
        
    }//GEN-LAST:event_sendjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adversejTable;
    private javax.swing.JComboBox drugCompanyjComboBox;
    private javax.swing.JComboBox drugjComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messagejTextField;
    private javax.swing.JComboBox networkjComboBox;
    private javax.swing.JButton sendjButton;
    // End of variables declaration//GEN-END:variables
}
