/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.doctorrole;

import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewEncounterHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEncounterHistoryJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    //private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    //private EcoSystem system;
    private Patient patient;
    public ViewEncounterHistoryJPanel(JPanel userProcessContainer,UserAccount account,Enterprise enterprise,Patient patient) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
       //this.doctorOrganization=doctorOrganization;
        this.enterprise=enterprise;
        //this.system=system;
        this.patient=patient;
        populate();
    }
    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) encounterjTable.getModel();
        dtm.setRowCount(0);
        
        for(Encounter encounter:patient.getEncounterList().getEncounterList()){
            Object[] row=new Object[2];
            row[0]=encounter;
            row[1]=encounter.getDoctor();
            dtm.addRow(row);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        encounterjTable = new javax.swing.JTable();
        viewencounterjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        viewmedicationjButton = new javax.swing.JButton();
        viewlabreportsjButton = new javax.swing.JButton();

        encounterjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter", "Doctor Name"
            }
        ));
        jScrollPane1.setViewportView(encounterjTable);

        viewencounterjButton.setText("View VitalSigns");
        viewencounterjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewencounterjButtonActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        viewmedicationjButton.setText("View Medication");
        viewmedicationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmedicationjButtonActionPerformed(evt);
            }
        });

        viewlabreportsjButton.setText("View Lab Reports");
        viewlabreportsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlabreportsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(viewencounterjButton)
                        .addGap(42, 42, 42)
                        .addComponent(viewmedicationjButton)
                        .addGap(44, 44, 44)
                        .addComponent(viewlabreportsjButton)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewencounterjButton)
                    .addComponent(viewmedicationjButton)
                    .addComponent(viewlabreportsjButton))
                .addGap(33, 33, 33)
                .addComponent(backjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewencounterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewencounterjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = encounterjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        Encounter encounter = (Encounter) encounterjTable.getValueAt(selectedRow, 0);
         ViewVitalSignsJPanel vvsjp = new ViewVitalSignsJPanel(userProcessContainer, encounter);
        userProcessContainer.add("ViewVitalSignsJPanel", vvsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
//        respratejTextField.setText(String.valueOf(encounter.getVitalsign().getResprate()));
//        heartratejTextField.setText(String.valueOf(encounter.getVitalsign().getHeartrate()));
//        sysbpjTextField.setText(String.valueOf(encounter.getVitalsign().getSysbp()));
//        tempjTextField.setText(String.valueOf(encounter.getVitalsign().getTemp()));
//        drugnamejTextField.setText(encounter.getMedication().getDrug().getDrugName());
//        dosagejTextField.setText(String.valueOf(encounter.getMedication().getDosage()));
//        testtypejTextField.setText(encounter.getLabTest().getTestType());
//        testresultjTextField.setText(encounter.getLabTest().getTestResult());
        
        
        
        
        
    }//GEN-LAST:event_viewencounterjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void viewmedicationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmedicationjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = encounterjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        Encounter encounter = (Encounter) encounterjTable.getValueAt(selectedRow, 0);
        if(encounter.getMedication().getDrug()==null){
            JOptionPane.showMessageDialog(null,"No medication available");
            return;
        }
         ViewMedicationJPanel vmjp = new ViewMedicationJPanel(userProcessContainer, encounter);
        userProcessContainer.add("ViewMedicationJPanel", vmjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewmedicationjButtonActionPerformed

    private void viewlabreportsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlabreportsjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = encounterjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        Encounter encounter = (Encounter) encounterjTable.getValueAt(selectedRow, 0);
         ViewLabReportsJPanel vlrjp = new ViewLabReportsJPanel(userProcessContainer, encounter);
        userProcessContainer.add("ViewLabReportsJPanel", vlrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewlabreportsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable encounterjTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewencounterjButton;
    private javax.swing.JButton viewlabreportsjButton;
    private javax.swing.JButton viewmedicationjButton;
    // End of variables declaration//GEN-END:variables
}
