/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.doctorrole;

import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Person.Doctor;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;

    public ViewPatientJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.doctorOrganization = doctorOrganization;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) doctortonurseworkrequestjTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (request instanceof NurseWorkRequest) {
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver() == null ? null : request.getReceiver();
                row[3] = request.getStatus();
                NurseWorkRequest req=(NurseWorkRequest)request;
                row[4] = req.getPatient().getFname();
                dtm.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctortonurseworkrequestjTable = new javax.swing.JTable();
        viewpatientjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        respratejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        heartratejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sysbpjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tempjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fnamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lnamejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phnumjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailidjTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dojjXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        assignjButton = new javax.swing.JButton();
        backJButton4 = new javax.swing.JButton();
        medicalprejButton = new javax.swing.JButton();
        referjButton = new javax.swing.JButton();
        labtestjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addvitalsignsjButton = new javax.swing.JButton();

        doctortonurseworkrequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reciever", "Status", "Patient's Name"
            }
        ));
        jScrollPane1.setViewportView(doctortonurseworkrequestjTable);

        viewpatientjButton.setText("View Patient");
        viewpatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpatientjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Respiratory Rate");

        respratejTextField.setEditable(false);

        jLabel2.setText("Heart Rate");

        heartratejTextField.setEditable(false);

        jLabel3.setText("Systolic BP");

        sysbpjTextField.setEditable(false);

        jLabel4.setText("Temperature");

        tempjTextField.setEditable(false);

        jLabel5.setText("First Name");

        fnamejTextField.setEditable(false);

        jLabel6.setText("Last Name");

        lnamejTextField.setEditable(false);

        jLabel7.setText("Age");

        agejTextField.setEditable(false);

        jLabel8.setText("City");

        cityjTextField.setEditable(false);

        jLabel9.setText("Phone Number");

        phnumjTextField.setEditable(false);

        jLabel10.setText("Email ID");

        emailidjTextField.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("View Patient");

        jLabel12.setText("Date of Admit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(agejTextField)
                    .addComponent(lnamejTextField)
                    .addComponent(fnamejTextField)
                    .addComponent(phnumjTextField)
                    .addComponent(emailidjTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysbpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dojjXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(dojjXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(respratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(heartratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(phnumjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(emailidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(sysbpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        assignjButton.setText("Assign to me");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });

        backJButton4.setText("<< Back");
        backJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton4ActionPerformed(evt);
            }
        });

        medicalprejButton.setText("Medical Prescription ");
        medicalprejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalprejButtonActionPerformed(evt);
            }
        });

        referjButton.setText("Refer To a Doctor");
        referjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referjButtonActionPerformed(evt);
            }
        });

        labtestjButton.setText("Lab Test Request");
        labtestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labtestjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("View Encounter History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addvitalsignsjButton.setText("Add Vital Signs");
        addvitalsignsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvitalsignsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backJButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewpatientjButton)
                                    .addComponent(assignjButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(labtestjButton)
                        .addGap(26, 26, 26)
                        .addComponent(medicalprejButton)
                        .addGap(35, 35, 35)
                        .addComponent(referjButton)
                        .addGap(47, 47, 47)
                        .addComponent(addvitalsignsjButton)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(viewpatientjButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labtestjButton)
                            .addComponent(medicalprejButton)
                            .addComponent(referjButton)
                            .addComponent(addvitalsignsjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backJButton4)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Work Request");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Diagonsing");
        populateTable();
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void viewpatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpatientjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Work Request");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        fnamejTextField.setText(request.getPatient().getFname());
        lnamejTextField.setText(request.getPatient().getLname());
        agejTextField.setText((String.valueOf(request.getPatient().getAge())));
        cityjTextField.setText(request.getPatient().getCity());
        phnumjTextField.setText(String.valueOf(request.getPatient().getNum()));
        emailidjTextField.setText(request.getPatient().getEmail());
        respratejTextField.setText(String.valueOf(request.getEncounter().getVitalsign().getResprate()));
        heartratejTextField.setText(String.valueOf(request.getEncounter().getVitalsign().getHeartrate()));
        sysbpjTextField.setText(String.valueOf(request.getEncounter().getVitalsign().getSysbp()));
        tempjTextField.setText(String.valueOf(request.getEncounter().getVitalsign().getTemp()));
        dojjXDatePicker.setDate(request.getEncounter().getDoj());


    }//GEN-LAST:event_viewpatientjButtonActionPerformed

    private void backJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton4ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton4ActionPerformed

    private void medicalprejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalprejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        MedicalPrescriptionJPanel mpjp = new MedicalPrescriptionJPanel(userProcessContainer, account, enterprise, system, request.getPatient(), request.getEncounter());
        userProcessContainer.add("MedicalPrescriptionJPanel", mpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_medicalprejButtonActionPerformed

    private void referjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
//        Encounter encounter=request.getPatient().getEncounterList().createEncounter();
//        Person p=account.getEmployee();
//        Doctor doctor=(Doctor)p;
//        encounter.setDoctor(doctor);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        DoctorReferenceJPanel drjp = new DoctorReferenceJPanel(userProcessContainer, account, enterprise, system, request.getPatient(), request.getEncounter());
        userProcessContainer.add("DoctorReferenceJPanel", drjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_referjButtonActionPerformed

    private void labtestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labtestjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        DoctorLabWorkRequestJPanel dlwjp = new DoctorLabWorkRequestJPanel(userProcessContainer, account,enterprise,request.getPatient(),request.getEncounter());
        userProcessContainer.add("DoctorLabWorkRequestJPanel", dlwjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_labtestjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        ViewEncounterHistoryJPanel vehjp = new ViewEncounterHistoryJPanel(userProcessContainer, account,enterprise,request.getPatient());
        userProcessContainer.add("ViewEncounterHistoryJPanel", vehjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addvitalsignsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvitalsignsjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctortonurseworkrequestjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
        NurseWorkRequest request = (NurseWorkRequest) doctortonurseworkrequestjTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("sent")){
            JOptionPane.showMessageDialog(null,"Please accept the request first");
            return;
        }
        AddVitalSignsJPanel avsjp = new AddVitalSignsJPanel(userProcessContainer, account,enterprise,request.getPatient(),request.getEncounter());
        userProcessContainer.add("AddVitalSignsJPanel", avsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addvitalsignsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvitalsignsjButton;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton assignjButton;
    private javax.swing.JButton backJButton4;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JTable doctortonurseworkrequestjTable;
    private org.jdesktop.swingx.JXDatePicker dojjXDatePicker;
    private javax.swing.JTextField emailidjTextField;
    private javax.swing.JTextField fnamejTextField;
    private javax.swing.JTextField heartratejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton labtestjButton;
    private javax.swing.JTextField lnamejTextField;
    private javax.swing.JButton medicalprejButton;
    private javax.swing.JTextField phnumjTextField;
    private javax.swing.JButton referjButton;
    private javax.swing.JTextField respratejTextField;
    private javax.swing.JTextField sysbpjTextField;
    private javax.swing.JTextField tempjTextField;
    private javax.swing.JButton viewpatientjButton;
    // End of variables declaration//GEN-END:variables
}
