/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.doctorrole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.QualityAnalystOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdverseEventWorkRequest;
import Business.WorkQueue.PatientFeedbackWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewPatientFeedBackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientFeedBackJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    public ViewPatientFeedBackJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system=system;
        populate();
        populateNetworkCombo();
    }
    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) feedbackjTable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest request:account.getWorkQueue().getWorkRequestList()){
            if(request instanceof PatientFeedbackWorkRequest){
                Object[] row=new Object[4];
                row[0]=request;
                row[1]=request.getSender();
                row[2]=request.getReceiver();
                row[3]=request.getStatus();
                dtm.addRow(row);
            }
        }
    }
    public void populateNetworkCombo(){
        networkjComboBox.removeAllItems();
        for(Network network:system.getNetworkList()){
            networkjComboBox.addItem(network);
        }
    }
    
    public void populateDrugCompanyCombo(Network network){
        drugCompanyjComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if(enterprise.getEnterpriseType().getValue().equals("DrugCompany"))
            drugCompanyjComboBox.addItem(enterprise);
        }
    }
    
    public void populateDrugCombo(DrugCompanyEnterprise enterprise){
        drugjComboBox.removeAllItems();
        for(Drug drug:enterprise.getDrugList().getDrugList()){
            drugjComboBox.addItem(drug);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackjTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagejTextArea = new javax.swing.JTextArea();
        assignjButton = new javax.swing.JButton();
        sendfeedbacktoQAjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        networkjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        drugCompanyjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        drugjComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        feedbackjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Patient's Name", "Doctor's Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(feedbackjTable);

        jButton1.setText("View Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messagejTextArea.setColumns(20);
        messagejTextArea.setRows(5);
        jScrollPane2.setViewportView(messagejTextArea);

        assignjButton.setText("Assign To Me");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });

        sendfeedbacktoQAjButton.setText("Send");
        sendfeedbacktoQAjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendfeedbacktoQAjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Network");

        networkjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Drug Company");

        drugCompanyjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugCompanyjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCompanyjComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Drug");

        drugjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("View Patient's Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(assignjButton)
                                .addComponent(jButton1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sendfeedbacktoQAjButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(networkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(drugCompanyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(drugjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(63, 63, 63)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel4)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugCompanyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(assignjButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(networkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(sendfeedbacktoQAjButton)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = feedbackjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        PatientFeedbackWorkRequest request=(PatientFeedbackWorkRequest)feedbackjTable.getValueAt(selectedRow,0);
        request.setReceiver(account);
        request.setStatus("Feedback Recieved");
        populate();
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = feedbackjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        PatientFeedbackWorkRequest request=(PatientFeedbackWorkRequest)feedbackjTable.getValueAt(selectedRow,0);
        if(request.getStatus().equals("Feedback Recieved")){
        messagejTextArea.setText(request.getMessage());
        }
        else{
            JOptionPane.showMessageDialog(null,"Please accept the feedback");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void networkjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBoxActionPerformed
        // TODO add your handling code here:
        Network network=(Network)networkjComboBox.getSelectedItem();
        if(network!=null){
            populateDrugCompanyCombo(network);
        }
    }//GEN-LAST:event_networkjComboBoxActionPerformed

    private void drugCompanyjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCompanyjComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise=(Enterprise)drugCompanyjComboBox.getSelectedItem();
        DrugCompanyEnterprise e1=(DrugCompanyEnterprise)enterprise;
        if(e1!=null){
            populateDrugCombo(e1);
        }
    }//GEN-LAST:event_drugCompanyjComboBoxActionPerformed

    private void sendfeedbacktoQAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendfeedbacktoQAjButtonActionPerformed
        // TODO add your handling code here:
        String message = messagejTextArea.getText();
        if (messagejTextArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Work Request");
            return;
        }
        int selectedRow = feedbackjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        PatientFeedbackWorkRequest request=(PatientFeedbackWorkRequest)feedbackjTable.getValueAt(selectedRow,0);
        Enterprise ent=(Enterprise)drugCompanyjComboBox.getSelectedItem();
        DrugCompanyEnterprise e1=(DrugCompanyEnterprise)ent;
        Drug d=(Drug)drugjComboBox.getSelectedItem();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        request.setDrug(d);
        
        
        Organization org=null;
        
        for(Organization o:e1.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof QualityAnalystOrganization){
                org=o;
                break;
            }
        }
        if(org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
       // System.out.println(account.getWorkQueue().getWorkRequestList().size());
        
        
    }//GEN-LAST:event_sendfeedbacktoQAjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton;
    private javax.swing.JComboBox drugCompanyjComboBox;
    private javax.swing.JComboBox drugjComboBox;
    private javax.swing.JTable feedbackjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messagejTextArea;
    private javax.swing.JComboBox networkjComboBox;
    private javax.swing.JButton sendfeedbacktoQAjButton;
    // End of variables declaration//GEN-END:variables
}
