/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugQualityAnalystRole;

import Business.EcoSystem;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.Organization.QualityAnalystOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdverseEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class QualityAnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QualityAnalystWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    private QualityAnalystOrganization qao;

    public QualityAnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, QualityAnalystOrganization qao, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        this.qao = qao;

        //populateTable();
    }

//    public void populateTable() {
//        DefaultTableModel dtm = (DefaultTableModel) adversejTable.getModel();
//        dtm.setRowCount(0);
//
//        for (WorkRequest request : qao.getWorkQueue().getWorkRequestList()) {
//            if (request instanceof AdverseEventWorkRequest) {
//                Object[] row = new Object[6];
//                row[0] = request;
//                row[1] = request.getSender();
//                row[2] = request.getReceiver();
//                row[3] = request.getStatus();
//                AdverseEventWorkRequest req = (AdverseEventWorkRequest) request;
//                row[4] = req.getDrug().getDrugName();
//                row[5] = req.getDrugCompany().getName();
//                dtm.addRow(row);
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewfeedbackjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Drug Quality Analyst Work Area");

        viewfeedbackjButton.setText("View Feedback");
        viewfeedbackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfeedbackjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Adverse Events");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(viewfeedbackjButton)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(viewfeedbackjButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewfeedbackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewfeedbackjButtonActionPerformed
        // TODO add your handling code here:
        
             ViewFeedbackJPanel vfjp = new ViewFeedbackJPanel(userProcessContainer, account, qao, enterprise, system);
            userProcessContainer.add("ViewFeedbackJPanel", vfjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_viewfeedbackjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ManageDoctorEventsJPanel mdejp = new ManageDoctorEventsJPanel(userProcessContainer, account, qao, enterprise, system);
            userProcessContainer.add("ManageDoctorEventsJPanel", mdejp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewfeedbackjButton;
    // End of variables declaration//GEN-END:variables
}
