/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DrugQualityAnalystRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.QualityAnalystOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientFeedbackWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFeedbackJPanel
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    private QualityAnalystOrganization qao;
    public ViewFeedbackJPanel(JPanel userProcessContainer, UserAccount account, QualityAnalystOrganization qao, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        this.qao = qao;
        populateTable();
    }
     public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) feedbackjTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : qao.getWorkQueue().getWorkRequestList()) {
            if (request instanceof PatientFeedbackWorkRequest) {
                Object[] row = new Object[6];
                row[0] = request;
                row[1] = request.getSender();
                //row[2] = request.getReceiver();
                row[2] = request.getStatus();
                PatientFeedbackWorkRequest req = (PatientFeedbackWorkRequest) request;
                row[3] = req.getDrug().getDrugName();
               
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackjTable = new javax.swing.JTable();
        viewfeedbackjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagejTextArea = new javax.swing.JTextArea();
        backjButton2 = new javax.swing.JButton();

        feedbackjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Doctor's Name", "Status", "Drug Name"
            }
        ));
        jScrollPane1.setViewportView(feedbackjTable);

        viewfeedbackjButton.setText("View Feedback Message");
        viewfeedbackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfeedbackjButtonActionPerformed(evt);
            }
        });

        messagejTextArea.setColumns(20);
        messagejTextArea.setRows(5);
        jScrollPane2.setViewportView(messagejTextArea);

        backjButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton2.setText("<< Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(viewfeedbackjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewfeedbackjButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewfeedbackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewfeedbackjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = feedbackjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        PatientFeedbackWorkRequest request=(PatientFeedbackWorkRequest)feedbackjTable.getValueAt(selectedRow,0);
        request.setStatus("Feedback Received");
        
        messagejTextArea.setText(request.getMessage());   
        
    }//GEN-LAST:event_viewfeedbackjButtonActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JTable feedbackjTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messagejTextArea;
    private javax.swing.JButton viewfeedbackjButton;
    // End of variables declaration//GEN-END:variables
}
