/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Person.Patient;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewEncounterHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEncounterHistoryJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;

    public ViewEncounterHistoryJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) encounterjTable.getModel();
        dtm.setRowCount(0);
        Person p = account.getEmployee();
        Patient patient = (Patient) p;

        for (Encounter e : patient.getEncounterList().getEncounterList()) {
            Object[] row = new Object[3];
            row[0] = e;
            System.out.println(e);
            System.out.println(e.getMedication());
            System.out.println(e.getMedication().getDrug());
            row[1] = e.getMedication().getDrug();
            row[2] = e.getDoctor();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        encounterjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        encounterjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter ID", "Drug Name", "Doctor Name"
            }
        ));
        jScrollPane1.setViewportView(encounterjTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Encounter History");

        viewjButton.setText("View Medication");
        viewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButtonActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(viewjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewjButton)
                .addGap(60, 60, 60)
                .addComponent(backjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = encounterjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
        } else {
            

            Encounter e = (Encounter) encounterjTable.getValueAt(selectedRow, 0);
            if(e.getMedication().getDrug()==null){
                JOptionPane.showMessageDialog(null,"There is NO drug to view Medication Guide");
                return;
            }
            String sideEffects=e.getMedication().getDrug().getMedicationGuide().getSideEffects();
            String notes=e.getMedication().getDrug().getMedicationGuide().getNotes();
            String donts=e.getMedication().getDrug().getMedicationGuide().getDonts();
            String previous=e.getMedication().getDrug().getMedicationGuide().getPreviousHistory();
            String precautions=e.getMedication().getDrug().getMedicationGuide().getPrecautions();
            System.out.println(sideEffects);
            if (sideEffects==null && notes==null&& donts==null && previous==null && precautions==null ) {
                JOptionPane.showMessageDialog(null,"No Medication Guide for this drug");
                return;
            }
                ViewMedicationGuideJPanel vehjp = new ViewMedicationGuideJPanel(userProcessContainer, account, enterprise, e.getMedication().getDrug().getMedicationGuide());
                userProcessContainer.add("ViewMedicationGuideJPanel", vehjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            
        }
    }//GEN-LAST:event_viewjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable encounterjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewjButton;
    // End of variables declaration//GEN-END:variables
}
