/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DrugManufacturerRole;

import Business.Drug.Drug;
import Business.Enterprise.DrugCompanyEnterprise;
import Business.Enterprise.Enterprise;
import UserInterface.DrugQualityAnalystRole.NotificationJPanel;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class DrugManufacturerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugManufacturerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private DrugCompanyEnterprise enterprise;
    Drug drug;
    public DrugManufacturerWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=(DrugCompanyEnterprise)enterprise;
        populate();
    }

    public void populate(){
        DefaultTableModel model = (DefaultTableModel)drugdetailsjTable.getModel();
        model.setRowCount(0);
        
        for(Drug drug:enterprise.getDrugList().getDrugList()){
            Object[] row = new Object[6];
            row[0]=drug;
            row[1]=drug.getManufactureDate();
            row[2]=drug.getExpiryDate();
            row[3]=drug.getCompostion();
            row[4]=drug.getWarning();
            row[5]=drug.getDrugCompany().getName();
            model.addRow(row);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drugnamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mfgdatejXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        expirydatejXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        compjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        warningjTextField = new javax.swing.JTextField();
        createdrugjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugdetailsjTable = new javax.swing.JTable();
        medicationguidejButton = new javax.swing.JButton();
        communicationplanjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Drug Manufacturer Work Area");

        jLabel2.setText("Drug Name");

        drugnamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                drugnamejTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("Mfg Date");

        mfgdatejXDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfgdatejXDatePickerActionPerformed(evt);
            }
        });
        mfgdatejXDatePicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mfgdatejXDatePickerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mfgdatejXDatePickerKeyTyped(evt);
            }
        });

        jLabel4.setText("Expiry Date");

        jLabel5.setText("Composition");

        jLabel6.setText("Warning");

        createdrugjButton.setText("Create Drug");
        createdrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdrugjButtonActionPerformed(evt);
            }
        });

        drugdetailsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Mfg Date", "Expiry Date", "Composition", "Warning", "Drug Company"
            }
        ));
        jScrollPane1.setViewportView(drugdetailsjTable);

        medicationguidejButton.setText("Create Medication Guide");
        medicationguidejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicationguidejButtonActionPerformed(evt);
            }
        });

        communicationplanjButton.setText("Create Communication Plan");
        communicationplanjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communicationplanjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(drugnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(expirydatejXDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mfgdatejXDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(compjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(warningjTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(createdrugjButton)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(communicationplanjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicationguidejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(compjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mfgdatejXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(warningjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(expirydatejXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdrugjButton)
                    .addComponent(medicationguidejButton))
                .addGap(18, 18, 18)
                .addComponent(communicationplanjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createdrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdrugjButtonActionPerformed
        // TODO add your handling code here:
        String drugName=drugnamejTextField.getText();
        Date mfgdate=mfgdatejXDatePicker.getDate();
        Date expiry=expirydatejXDatePicker.getDate();
        String compostion=compjTextField.getText();
        String warning=warningjTextField.getText();
        if(drugName.isEmpty()||mfgdate==null||expiry==null||compostion.isEmpty()||warning.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all details");
            return;
        }
        for(Drug drug:enterprise.getDrugList().getDrugList()){
            if(drug.getDrugName().equals(drugName)){
                JOptionPane.showMessageDialog(null, "Drug already created");
                return;
            }
        }
        if(expiry.before(mfgdate)){
            JOptionPane.showMessageDialog(null,"Expiry date should be after Mfg Date");
            return;
        }
        drug=enterprise.getDrugList().createDrug();
        drug.setDrugName(drugName);
        drug.setManufactureDate(mfgdate);
        drug.setExpiryDate(expiry);
        drug.setCompostion(compostion);
        drug.setWarning(warning);
        drug.setDrugCompany(enterprise);
        populate();
        
           
        
        
    }//GEN-LAST:event_createdrugjButtonActionPerformed

    private void medicationguidejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicationguidejButtonActionPerformed
        // TODO add your handling code here:
//        if(drug==null){
//            JOptionPane.showMessageDialog(null, "Please Create a Drug!!");
//            return;
//        }
        int selectedRow = drugdetailsjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        Drug drug=(Drug)drugdetailsjTable.getValueAt(selectedRow,0);
        
        MedicationGuideJPanel mgjp = new MedicationGuideJPanel(userProcessContainer,enterprise,drug);
        userProcessContainer.add("MedicationGuideJPanel", mgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_medicationguidejButtonActionPerformed

    private void communicationplanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communicationplanjButtonActionPerformed
        // TODO add your handling code here:
//        if(drug==null){
//           JOptionPane.showMessageDialog(null, "Please Create a Drug!!");
//            return; 
//        }
        int selectedRow = drugdetailsjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row");
            return;
        }
        Drug drug=(Drug)drugdetailsjTable.getValueAt(selectedRow,0);
          CommunicationPlanJPanel cpjp = new CommunicationPlanJPanel(userProcessContainer,enterprise,drug);
        userProcessContainer.add("CommunicationPlanJPanel", cpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_communicationplanjButtonActionPerformed

    private void drugnamejTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugnamejTextFieldKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!(Character.isLetter(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_drugnamejTextFieldKeyTyped

    private void mfgdatejXDatePickerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mfgdatejXDatePickerKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!(Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_mfgdatejXDatePickerKeyTyped

    private void mfgdatejXDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfgdatejXDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgdatejXDatePickerActionPerformed

    private void mfgdatejXDatePickerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mfgdatejXDatePickerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgdatejXDatePickerKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton communicationplanjButton;
    private javax.swing.JTextField compjTextField;
    private javax.swing.JButton createdrugjButton;
    private javax.swing.JTable drugdetailsjTable;
    private javax.swing.JTextField drugnamejTextField;
    private org.jdesktop.swingx.JXDatePicker expirydatejXDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton medicationguidejButton;
    private org.jdesktop.swingx.JXDatePicker mfgdatejXDatePicker;
    private javax.swing.JTextField warningjTextField;
    // End of variables declaration//GEN-END:variables
}
